import React from "react";
import styles from "./termsAndConditions.module.scss";

const termsPoints = [
  {
    title: "Acceptance of Terms",
    description:
      "By accessing this website, you agree to comply with these Terms and Conditions.",
  },
  {
    title: "Services",
    description:
      "Lunar Wolf provides automated Forex EA software access, technical support, and information related to EA services. Lunar Wolf does not provide fund management, investment advisory, or guaranteed-return services.",
  },
  {
    title: "Account Access",
    description:
      "Users who participate in EA services may voluntarily provide trading account access for the purpose of executing trades through automated systems.",
  },
  {
    title: "Intellectual Property",
    description:
      "All software, strategies, algorithms, and content on this website are the exclusive property of Lunar Wolf. Users may not copy, distribute, or replicate any part of the system.",
  },
  {
    title: "Minimum Trading Capital",
    description:
      "EA activation may require a minimum trading capital in the user’s own broker account, as stated in the applicable plan. Lunar Wolf does not receive, hold, or manage this capital.",
  },
  {
    title: "Performance Fee",
    description:
      "A performance-based fee may apply only on eligible profit generated by closed profitable trades executed through Lunar Wolf EA / copy-trading activity, according to the selected plan and Lunar Wolf service agreement. The fee is not charged on deposits, withdrawals, account balance, unused capital, losing trades, broker swap, or broker commission.",
  },
  {
    title: "User Responsibility",
    description:
      "Users are responsible for ensuring that forex trading, automated trading, broker selection, deposits, withdrawals, and referral rewards are permitted under the laws and regulations of their country of residence.",
  },
  {
    title: "Modification of Services",
    description:
      "Lunar Wolf reserves the right to modify, suspend, or discontinue any part of the service without prior notice.",
  },
  {
    title: "Limitation of Liability",
    description:
      "Lunar Wolf will not be responsible for trading losses, technical issues, or any financial damages arising from the use of the website or services.",
  },

];

const TermsAndConditions = () => {
  return (
    <section className={styles.termsWrapper}>
      <div className={styles.container}>
        <h1 className={styles.title}>Terms & Conditions</h1>

        {/* <p className={styles.effectiveDate}>
            Effective Date: __________
          </p> */}

        <p className={styles.introText}>
          These Terms & Conditions govern the use of the Lunar Wolf website and
          services.
        </p>

        <ul className={styles.termsList}>
          {termsPoints.map((point) => (
            <li key={point.title}>
              <p className={styles.sectionTitle}>{point.title}</p>
              <p className={styles.sectionDesc}>{point.description}</p>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
};

export default TermsAndConditions;
