'use client'
import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion';
import styles from './faqSection.module.scss';
import DownIcon from '@/icons/downIcon';
import classNames from 'classnames';

const leftFaqs = [
    {
        question: "WHAT IS LUNAR WOLF EA?",
        answer: "Lunar Wolf EA is EURUSD-focused automated Forex trading software designed for structured execution through user-controlled broker accounts."
    },
    {
        question: "How does Lunar Wolf earn?",
        answer: "Lunar Wolf may charge a performance-based fee only on eligible net profits generated through the EA, according to the selected plan and service agreement."
    },
    {
        question: "How do referral rewards work?",
        answer: (
            <>
                Referral rewards may be paid from eligible profit-share revenue or eligible IB revenue generated by active referred accounts. Rewards are not paid for joining, registration, or recruitment alone.
            </>
        )
    },
    {
        question: "Is Lunar Wolf available worldwide?",
        answer: "Yes. Lunar Wolf is available to users in many countries. Users are solely responsible for ensuring that their use of the EA, forex trading, broker selection, deposits, withdrawals, and referral participation comply with the laws and regulations of their country of residence."
    },
    {
        question: "IS PERFORMANCE GUARANTEED?",
        answer: (
            <>
                No. Forex trading involves risk, and no automated system can guarantee profits. Results may vary due to market volatility, spreads, slippage, leverage, broker execution, latency, and technical conditions.
            </>
        )
    },
    {
        question: "HOW DOES BROKER SELECTION WORK?",
        answer: (
            <>
                Lunar Wolf supports multiple broker environments to provide users with flexibility and reduce dependency on a single provider.
                <br /><br />
                Users choose and open their own broker account from supported options, complete verification directly with the broker, fund the account independently, and connect it to the Lunar Wolf system.
                <br /><br />
                This structure helps maintain user control while allowing flexibility in execution environments.
            </>
        )
    },
    {
        question: "Is Lunar Wolf an MLM or investment scheme?",
        answer: (
            <>
                No. Lunar Wolf is not an investment scheme, fund-collection model, or guaranteed-income program. Lunar Wolf provides Forex EA software access, setup support, and related technical services. The referral structure is optional, and rewards are linked to eligible active EA usage, trading-related revenue, achieved qualification, and Lunar
                Wolf service terms. Rewards are not paid for registration or recruitment alone.
            </>
        )
    },
    {
        question: " Are referral rewards paid just for adding new users?",
        answer: (
            <>
                No. Lunar Wolf does not pay rewards for registration or recruitment alone. Referral rewards may apply only when referred users maintain eligible active EA accounts and generate eligible trading-related revenue according
                to Lunar Wolf qualification rules and service terms.
            </>
        )
    },
    {
        question: " How does the 5-level referral reward structure work?",
        answer: (
            <>
                Eligible referral rewards may extend up to 5 levels, subject to achieved qualification, active EA account status, eligible trading-related revenue, and Lunar Wolf service terms. Each level has its own qualification requirement and reward percentage. Not
                every referred user or level automatically qualifies for rewards.
            </>
        )
    },
    {
        question: "What are the two eligible reward streams in Lunar Wolf?",
        answer: (
            <>
                Lunar Wolf may offer two eligible reward streams: Profit Sharing rewards and IB-Sharing rewards. Profit Sharing rewards are linked to eligible profitable Lunar Wolf EA / copy-trading activity, while IB-Sharing rewards are linked to eligible broker-side IB income received and confirmed by Lunar Wolf.
                Both are subject to qualification rules and service terms.
            </>
        )
    },
    {
        question: "Is Lunar Wolf suitable for beginners?",
        answer: (
            <>
                Lunar Wolf is designed to reduce manual monitoring and support structured EURUSD automation. However, Forex trading still involves risk. Beginners should understand basic trading risk, broker account setup,
                leverage, drawdown, and capital exposure before using any automated trading system.
            </>
        )
    },
    {
        question: "Can Lunar Wolf EA lose money?",
        answer: (
            <>
                Yes. Forex trading and automated EA trading involve risk. Market volatility, spreads, slippage, broker execution, liquidity, technical issues, and changing market conditions can affect results. No
                automated system can guarantee profits or prevent losses.
            </>
        )
    },
];

const rightFaqs = [
    {
        question: "DO I NEED TRADING EXPERIENCE TO USE IT?",
        answer: (
            <>
                No advanced trading experience is required.
                <br /><br />
                However, users should understand that automated trading still involves market risk and remain responsible for broker selection, capital allocation, and account decisions.
            </>
        )
    },
    {
        question: "HOW MUCH PROFIT CAN I EXPECT?",
        answer: (
            <>
                Trading outcomes vary depending on market conditions, broker execution, volatility, and account configuration.
                <br /><br />
                Past performance does not guarantee future results, and no specific return levels are promised.
            </>
        )
    },
    {
        question: " Does the EA operate 24/5?",
        answer: (
            <>
                LUNAR WOLF EA monitors markets during active forex trading sessions and executes only when predefined conditions are met.
                <br /><br />
                Continuous monitoring does not guarantee continuous trading activity.
            </>
        )
    },
    {
        question: "DOES LUNAR WOLF HOLD MY FUNDS?",
        answer: (
            <>
                No. Lunar Wolf does not hold, deposit, withdraw, custody, or manage client funds. Users trade through their own broker accounts and remain responsible for deposits, withdrawals, broker selection, account settings, and capital management.
            </>
        )
    },
    {
        question: "CAN RESULTS VARY ACROSS BROKERS?",
        answer: (
            <>
                Yes, Live trading performance can vary between brokers due to factors such as:
                <br /><br />
                • Execution speed
                <br />
                • Spread conditions
                <br />
                • Slippage
                <br />
                • Liquidity availability
                <br />
                • Server latency
                <br />
                • Market execution differences
                <br /><br />
                Because real-world conditions differ across broker environments, live outcomes may not exactly match historical simulations or performance shown elsewhere.
            </>
        )
    },
    {
        question: "WHAT RISKS SHOULD USERS UNDERSTAND?",
        answer: (
            <>
                Trading foreign exchange involves substantial risk and may not be suitable for every user.
                <br /><br />
                Key risks include:
                <br /><br />
                • Market volatility
                <br />
                • Drawdowns and losing periods
                <br />
                • Broker execution differences
                <br />
                • Spread expansion and slippage
                <br />
                • Liquidity changes
                <br />
                • Technical interruptions
                <br />
                • Historical performance limitations
                <br /><br />
                Users should only trade with capital they can afford to risk and should understand that losses are possible.
                <br /><br />
                Lunar Wolf is designed as a structured trading framework and not a guaranteed return product.

            </>
        )
    },
    {
        question: "Does Lunar Wolf collect deposits or manage client funds?",
        answer: (
            <>
                No. Lunar Wolf does not collect, hold, manage, deposit, withdraw, custody, or control client funds. Users trade through their own broker accounts and remain responsible for their deposits,
                withdrawals, account access, risk settings, and trading capital.
            </>
        )
    },
    {
        question: "Why are supported brokers required?",
        answer: (
            <>
                Supported brokers are required because Lunar Wolf EA setup, account tracking, and IB-sharing eligibility depend on broker compatibility, EA access, and tracking availability. Users remain free to control their own broker accounts, deposits,
                withdrawals, and trading capital. Future supported brokers may be added by Lunar Wolf.
            </>
        )
    },
    {
        question: "What does Myfxbook tracking mean?",
        answer: (
            <>
                Myfxbook tracking is used to provide third-party performance visibility for selected live trading accounts. It helps users review trading history, drawdown, trading activity, and performance behavior. Myfxbook tracking is provided
                for transparency only and does not guarantee future results.
            </>
        )
    },
    {
        question: "Does 3 months free access mean no charges at all?",
        answer: (
            <>
                During the 3-month pre-launch period, Lunar Wolf EA usage may be provided free for selected users. No Profit Share Fee will be charged during this period, and Profit Sharing referral rewards will not be distributed. Eligible IB-Sharing benefits may still apply according to
                active EA usage, achieved qualification, and Lunar Wolf service terms.
            </>
        )
    },
    {
        question: "Can users withdraw their funds anytime?",
        answer: (
            <>
                Users control their own broker accounts and withdrawals are handled directly through their broker, subject to broker rules, account status, open trades, margin requirements, and applicable terms. Lunar
                Wolf does not process or control withdrawals.
            </>
        )
    },
    {
        question: "What happens if a referred user stops trading or disconnects the EA?",
        answer: (
            <>
                If a referred user stops trading, disconnects the EA, becomes inactive, or no longer meets eligibility requirements, related rewards may reduce, pause, or stop according
                to Lunar Wolf qualification rules and service terms.
            </>
        )
    },

];

const FaqItem = ({ item, isOpen, onClick }) => {
    return (
        <div className={styles.mainFaq} onClick={onClick} style={{ cursor: 'pointer' }}>
            <div className={styles.faqheader}>
                <h3>{item.question}</h3>
                <motion.div
                    className={styles.iconAlignment}
                    animate={{ rotate: isOpen ? 180 : 0 }}
                    transition={{ duration: 0.3, ease: "easeInOut" }}
                >
                    <DownIcon />
                </motion.div>
            </div>
            <AnimatePresence initial={false}>
                {isOpen && (
                    <motion.div
                        className={styles.faqbody}
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.4, ease: "easeInOut" }}
                        style={{ overflow: 'hidden' }}
                    >
                        <div className={styles.spacing}>
                            <p>{item.answer}</p>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}

export default function FaqSection({ bgblack }) {
    const [openIndex, setOpenIndex] = useState(null); // All FAQs closed by default

    return (
        <div className={classNames(styles.faqSection, bgblack ? styles.bgblack : "")}>
            <div className={styles.leftrightSpacing}>
                <div className={styles.title}>
                    <h2>
                        Frequently Asked Questions
                    </h2>
                </div>
                <div className={styles.grid}>
                    <div className={styles.items}>
                        {leftFaqs.map((faq, idx) => (
                            <FaqItem
                                key={idx}
                                item={faq}
                                isOpen={openIndex === idx}
                                onClick={() => setOpenIndex(openIndex === idx ? null : idx)}
                            />
                        ))}
                    </div>
                    <div className={styles.items}>
                        {rightFaqs.map((faq, idx) => {
                            const actualIdx = idx + leftFaqs.length;
                            return (
                                <FaqItem
                                    key={actualIdx}
                                    item={faq}
                                    isOpen={openIndex === actualIdx}
                                    onClick={() => setOpenIndex(openIndex === actualIdx ? null : actualIdx)}
                                />
                            )
                        })}
                    </div>
                </div>
            </div>
        </div>
    )
}
