'use client'
import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion';
import styles from './faqSection.module.scss';
import DownIcon from '@/icons/downIcon';

const leftFaqs = [
    {
        question: "WHAT IS LUNAR WOLF EA?",
        answer: "Lunar Wolf EA is an automated Forex trading robot that trades on your MT5 account. It analyzes the market, opens, manages, and closes trades automatically, using a proven strategy for consistent performance."
    },
    {
        question: "HOW DOES LUNAR WOLF EA MAKE PROFIT?",
        answer: "It uses advanced algorithms and AI to identify high-probability trading setups and executes them with strict risk management."
    },
    {
        question: "IS MY MONEY SAFE?",
        answer: "Yes, your money stays in your own brokerage account. The EA only has permission to trade, not to withdraw or transfer funds."
    },
    {
        question: "HOW IS THE 30% FEE DEDUCTED?",
        answer: "The 30% performance fee is calculated on a high-water mark basis and is automatically deducted only when your account makes a net profit."
    },
    {
        question: "WHAT PLATFORM DOES LUNAR WOLF WORK ON?",
        answer: "Lunar Wolf EA is exclusively designed to work seamlessly with the MetaTrader 5 (MT5) platform."
    }
];

const rightFaqs = [
    {
        question: "DO I NEED TRADING EXPERIENCE TO USE IT?",
        answer: "No prior trading experience is required. The bot is fully automated, meaning it handles all market analysis and execution."
    },
    {
        question: "HOW MUCH PROFIT CAN I EXPECT?",
        answer: "While past performance does not guarantee future results, our proven strategies aim for consistent, long-term growth depending on market conditions."
    },
    {
        question: "WHAT IS THE 30% PROFIT SHARING SYSTEM?",
        answer: "We align our success with yours. You keep 70% of the profits generated by the bot, and 30% is shared as a performance fee."
    },
    {
        question: "CAN I USE THE EA ON MULTIPLE ACCOUNTS?",
        answer: "Yes, you can connect multiple MT5 accounts depending on the licensing tier or subscription plan you choose."
    },
    {
        question: "DOES THE EA WORK 24/7?",
        answer: "The EA monitors the market 24/5 during active forex trading hours, automatically adapting to varying market conditions."
    }
];

const FaqItem = ({ item, isOpen, onClick }) => {
    return (
        <div className={styles.mainFaq} onClick={onClick} style={{ cursor: 'pointer' }}>
            <div className={styles.faqheader}>
                <h3>{item.question}</h3>
                <motion.div
                    className={styles.iconAlignment}
                    animate={{ rotate: isOpen ? 180 : 0 }}
                    transition={{ duration: 0.3, ease: "easeInOut" }}
                >
                    <DownIcon />
                </motion.div>
            </div>
            <AnimatePresence initial={false}>
                {isOpen && (
                    <motion.div
                        className={styles.faqbody}
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.4, ease: "easeInOut" }}
                        style={{ overflow: 'hidden' }}
                    >
                        <div className={styles.spacing}>
                            <p>{item.answer}</p>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}

export default function FaqSection() {
    const [openIndex, setOpenIndex] = useState(0); // Open the first FAQ by default

    return (
        <div className={styles.faqSection}>
            <div className={styles.leftrightSpacing}>
                <div className={styles.title}>
                    <h2>
                        Frequently Asked Questions
                    </h2>
                </div>
                <div className={styles.grid}>
                    <div className={styles.items}>
                        {leftFaqs.map((faq, idx) => (
                            <FaqItem
                                key={idx}
                                item={faq}
                                isOpen={openIndex === idx}
                                onClick={() => setOpenIndex(openIndex === idx ? null : idx)}
                            />
                        ))}
                    </div>
                    <div className={styles.items}>
                        {rightFaqs.map((faq, idx) => {
                            const actualIdx = idx + leftFaqs.length;
                            return (
                                <FaqItem
                                    key={actualIdx}
                                    item={faq}
                                    isOpen={openIndex === actualIdx}
                                    onClick={() => setOpenIndex(openIndex === actualIdx ? null : actualIdx)}
                                />
                            )
                        })}
                    </div>
                </div>
            </div>
        </div>
    )
}
